schema_version = "1.0.0"

# LcL Tools - Mesh Intersection Detection Extension
id = "lcl_tools"
version = "1.0.0"
name = "LcL Tools"
tagline = "LcL Tools (模型穿插检测)"
maintainer = "LcL"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2026 LcL",
]

tags = ["Mesh"]
