schema_version = "1.0.0"

id = "lcl_tools"
version = "1.0.0"
name = "lcl_tools"
tagline = "LcL 工具"
maintainer = "lcl"
type = "add-on"

tags = ["Animation", "Sequencer"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
